---
title: "W241 Final Project: Randomization"
author: 
  - "Nishanth Nair, Samir Datta, Kim Vignola, Kathleen Wang"

date: \today

fontsize: 12pt

header-includes:
   - \usepackage{amsmath}
   - \usepackage{xcolor}

output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
#Specify path to download random assignments
download_path = "."


#Randomize the index with 1 or 0
randomize <- function() { 
  sample(c(rep(0,20),rep(1,20)))
}

#Randomize 30 company assignments (Phase 2: East Coast)
randomize30 <- function() { 
  sample(c(rep(0,15),rep(1,15)))
}

#Function to get random assignments
assign_attributes <- function(company_id,company,stagger){
  good <- company_id*company
  bad <- company_id*(1-company) 
  stagger_good <- stagger[which(good > 0)]
  stagger_bad  <- stagger[which(bad > 0)]

  return (data.frame(good = good[good != 0],
                     bad = bad[bad != 0],
                     stagger_good = stagger_good,
                     stagger_bad = stagger_bad))
}


#Get assignments for users in CA
company_id_ca <- c(81:120)
random_ca <- randomize()
stagger_ca <- randomize()

user_1 = assign_attributes(company_id_ca,random_ca,stagger_ca)
write.table(user_1,paste(download_path,"/ph2_user1.txt",sep=""), sep="\t")

user_2 = assign_attributes(company_id_ca,(1-random_ca),(1-stagger_ca))
write.table(user_2, paste(download_path,"/ph2_user2.txt",sep=""), sep="\t") 

#Get assignments for users in NY
random_ny <- randomize30()
stagger_ny <- randomize30()
company_id_ny <- c(121:150)

user_3 = assign_attributes(company_id_ny,random_ny,stagger_ny)
write.table(user_3, paste(download_path,"/ph2_user3.txt",sep=""), sep="\t")

user_4 = assign_attributes(company_id_ny,(1-random_ny),(1-stagger_ny))
write.table(user_4, paste(download_path,"/ph2_user4.txt",sep=""), sep="\t")
```
